[package]
name = "rust-playground"
version = "0.1.0"
authors = ["Andreas Schaeffer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.9.0"
rand = "0.8.0"
